# tensorflow 2.0  
- google公司
- 深度学习框架 定位就是工具  核心 keras

---

TensorFlow 2.0 与 1.0 的主要区别体现在易用性、API 设计、执行模式以及生态系统整合等方面。以下是详细的对比：

### **1. 执行模式：Eager Execution 默认启用**
- **TensorFlow 1.x**  
  - 基于**静态计算图**，需先定义计算图，再通过 `tf.Session` 执行。
  - 代码冗余，调试困难（如使用 `tf.Print` 或 `sess.run()` 查看中间结果）。

- **TensorFlow 2.0**  
  - 默认启用 **Eager Execution**（即时执行），代码逐行运行，如同普通 Python。
  - 动态图更易调试，支持直接打印变量值。
  - 通过 `@tf.function` 将 Python 函数转换为静态图，兼顾性能与灵活性（基于 AutoGraph）。



### **2. API 简化与 Keras 整合**
- **TensorFlow 1.x**  
  - API 分散且冗余：存在 `tf.layers`、`tf.contrib`、`slim` 等多个模块。
  - `tf.contrib` 包含实验性功能，但稳定性差，2.0 中已移除。

- **TensorFlow 2.0**  
  - **Keras 成为官方高阶 API**：模型构建、训练、评估更简洁。
  - 清理冗余 API，核心功能整合到 `tf.keras`、`tf.data` 等模块。
  - 示例对比：
    ```python
    # TF 1.x（需手动管理图与会话）
    x = tf.placeholder(tf.float32, shape=[None, 784])
    y = tf.layers.dense(x, 10)
    # TF 2.0（Keras 风格）
    model = tf.keras.Sequential([tf.keras.layers.Dense(10, input_shape=(784,))])
    ```



### **3. 移除冗余机制**
- **TensorFlow 1.x**  
  - 需显式使用 `tf.Session`、`tf.placeholder`、`tf.global_variables_initializer()`。
  - 变量初始化依赖 `sess.run(tf.global_variables_initializer())`。

- **TensorFlow 2.0**  
  - **移除 `tf.Session` 和 `tf.placeholder`**：无需手动管理会话或占位符。
  - 变量即时初始化，代码更简洁。



### **4. 训练流程优化**
- **TensorFlow 1.x**  
  - 手动定义优化器、梯度计算（如 `tf.gradients`）和更新操作。
  - 自定义训练循环复杂。

- **TensorFlow 2.0**  
  - **推荐使用 `model.fit()`**：内置训练流程，适合常见场景。
  - **灵活自定义训练**：结合 `GradientTape` 和优化器：
    ```python
    with tf.GradientTape() as tape:
        predictions = model(x)
        loss = loss_fn(y, predictions)
    gradients = tape.gradient(loss, model.trainable_variables)
    optimizer.apply_gradients(zip(gradients, model.trainable_variables))
    ```



### **5. 数据输入与预处理**
- **TensorFlow 1.x**  
  - 使用 `tf.data` 或 `feed_dict` 输入数据，但集成不够紧密。

- **TensorFlow 2.0**  
  - **强化 `tf.data`**：高效数据管道，支持并行预处理。
  - 无缝对接 Keras 模型：
    ```python
    dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train)).batch(32)
    model.fit(dataset, epochs=5)
    ```



### **6. 模型保存与部署**
- **TensorFlow 1.x**  
  - 使用 `tf.saved_model` 或 `checkpoint` 保存模型，格式复杂。

- **TensorFlow 2.0**  
  - **统一使用 `SavedModel` 格式**：跨平台部署（TensorFlow Lite、TensorFlow.js、TensorFlow Serving）。
  - 简化保存与加载：
    ```python
    model.save('model_path')  # 保存
    loaded_model = tf.keras.models.load_model('model_path')  # 加载
    ```



### **7. 兼容性与迁移工具**
- **TensorFlow 1.x 兼容性**  
  - 2.0 提供 `tf.compat.v1` 模块支持旧版 API，但鼓励迁移。
  - 使用脚本 `tf_upgrade_v2` 自动转换 1.x 代码。



### **8. 性能优化**
- **TensorFlow 2.0**  
  - Eager Execution 下，通过 `@tf.function` 将关键代码转为静态图，接近 1.x 性能。
  - 优化运行时和硬件支持（如 GPU/TPU 加速）。



### **总结：TensorFlow 2.0 的优势**
- **更易用**：Eager Execution、Keras API、简化代码。
- **更灵活**：支持动态图与静态图混合编程。
- **更统一**：API 清理与模块整合。
- **更高效**：`tf.data` 和 `tf.function` 提升性能。
- **更好的生态**：强化部署工具链（TFLite、TF.js 等）。



### **迁移建议**
- 新项目直接使用 TensorFlow 2.0。
- 旧项目逐步替换冗余 API（如 `tf.Session`、`tf.placeholder`），利用 `tf.function` 优化性能。
- 参考官方迁移指南：[TensorFlow 2.0 Migration Guide](https://www.tensorflow.org/guide/migrate)。

---

In [5]:
import tensorflow as tf
import numpy as np

In [6]:
tf.__version__

'2.19.0'

In [7]:
# tensor 张量
x1 = [[1,2] , [2,3]]
m = tf.matmul(x1,x1)
m

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5,  8],
       [ 8, 13]], dtype=int32)>

In [8]:
x2 = tf.constant([[1,9] , [3,6]])
x2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 9],
       [3, 6]], dtype=int32)>

In [9]:
x3 = tf.add(x2,1)  # 对每个元素做加法
x3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2, 10],
       [ 4,  7]], dtype=int32)>

In [10]:
# 可以和numpy转化
x3.numpy()

array([[ 2, 10],
       [ 4,  7]], dtype=int32)

In [11]:
x = tf.cast(x3 , tf.float32)
x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 2., 10.],
       [ 4.,  7.]], dtype=float32)>

In [12]:
x4 = np.ones([2,2])
print(x4)
x5 = tf.multiply(x1,2)
x5

[[1. 1.]
 [1. 1.]]


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [4, 6]], dtype=int32)>


# **常用基础操作分类**
#### **(1) 逐元素运算**
- `tf.add(x, y)` 或 `x + y`：逐元素加法。
- `tf.subtract(x, y)` 或 `x - y`：逐元素减法。
- `tf.divide(x, y)` 或 `x / y`：逐元素除法。
- `tf.math.log(x)`：自然对数。
- `tf.square(x)`：平方。

#### **(2) 矩阵运算**
- `tf.tf.multiply(a, b)` ：矩阵逐元素相乘。
- `tf.matmul(a, b)` 或 `a @ b`：矩阵乘法。
- `tf.linalg.inv(a)`：矩阵求逆（需可逆方阵）。
- `tf.transpose(a)`：矩阵转置。

#### **(3) 归约操作**
- `tf.reduce_sum(x, axis)`：沿指定轴求和。
- `tf.reduce_mean(x, axis)`：沿指定轴求均值。
- `tf.reduce_max(x, axis)`：沿指定轴求最大值。
- `tf.reduce_min(x, axis)`：沿指定轴求最小值。

#### **(4) 激活函数**
- `tf.nn.relu(x)`：ReLU 激活。
- `tf.nn.sigmoid(x)`：Sigmoid 激活。
- `tf.nn.softmax(x, axis)`：Softmax 归一化。

#### **(5) 形状操作**
- `tf.reshape(x, new_shape)`：调整张量形状。
  ```python
  a = tf.ones([3, 4])
  b = tf.reshape(a, [2, 6])  # 形状变为 (2, 6)
  ```
- `tf.concat([a, b], axis)`：沿指定轴拼接张量。
- `tf.split(x, num_split, axis)`：分割张量。

#### **(6) 张量创建**
- `tf.constant(value)`：创建常量张量。
- `tf.zeros(shape)` 和 `tf.ones(shape)`：全零/全一张量。
- `tf.random.normal(shape)`：正态分布随机张量。
- `tf.Variable(initial_value)`：创建可训练变量。

#### **(7) 梯度计算**
- 使用 `tf.GradientTape` 自动求导：
  ```python
  x = tf.Variable(3.0)
  with tf.GradientTape() as tape:
      y = x ** 2
  dy_dx = tape.gradient(y, x)  # 输出 6.0
  ```

---


# Keras.layers

### **1. 基础层**
| 层 | 说明 | 代码示例 |
|------|------|------|
| `Dense` | 全连接层，常用于 MLP（多层感知机） | `layers.Dense(64, activation='relu')` |
| `Activation` | 独立激活函数层 | `layers.Activation('relu')` |
| `Flatten` | 把多维数据展平成一维 | `layers.Flatten()` |
| `Reshape` | 调整输入形状 | `layers.Reshape((28, 28, 1))` |
| `Permute` | 交换张量维度顺序 | `layers.Permute((2, 1, 3))` |
| `Lambda` | 允许自定义计算逻辑 | `layers.Lambda(lambda x: x ** 2)` |



### **2. 卷积层（CNN 相关）**
适用于图像处理任务。

| 层 | 说明 | 代码示例 |
|------|------|------|
| `Conv1D` | 1D 卷积层（用于时间序列） | `layers.Conv1D(32, 3, activation='relu')` |
| `Conv2D` | 2D 卷积层（用于图像） | `layers.Conv2D(64, (3,3), activation='relu')` |
| `Conv3D` | 3D 卷积层（用于 3D 数据，如医学影像） | `layers.Conv3D(64, (3,3,3), activation='relu')` |
| `SeparableConv2D` | 深度可分离卷积，提高计算效率 | `layers.SeparableConv2D(32, (3,3), activation='relu')` |
| `DepthwiseConv2D` | 深度卷积（每个通道独立卷积） | `layers.DepthwiseConv2D((3,3))` |



### **3. 池化层（Pooling）**
用于降维，减少计算量，防止过拟合。

| 层 | 说明 | 代码示例 |
|------|------|------|
| `MaxPooling1D` | 1D 最大池化 | `layers.MaxPooling1D(2)` |
| `MaxPooling2D` | 2D 最大池化 | `layers.MaxPooling2D((2,2))` |
| `MaxPooling3D` | 3D 最大池化 | `layers.MaxPooling3D((2,2,2))` |
| `AveragePooling2D` | 2D 平均池化 | `layers.AveragePooling2D((2,2))` |
| `GlobalMaxPooling2D` | 全局最大池化 | `layers.GlobalMaxPooling2D()` |
| `GlobalAveragePooling2D` | 全局平均池化 | `layers.GlobalAveragePooling2D()` |



### **4. 循环神经网络层（RNN）**
适用于时间序列、自然语言处理等任务。

| 层 | 说明 | 代码示例 |
|------|------|------|
| `SimpleRNN` | 简单 RNN | `layers.SimpleRNN(32, return_sequences=True)` |
| `LSTM` | 长短时记忆网络 | `layers.LSTM(64, return_sequences=True)` |
| `GRU` | 门控循环单元（比 LSTM 计算更快） | `layers.GRU(64, return_sequences=True)` |
| `Bidirectional` | 双向 RNN | `layers.Bidirectional(layers.LSTM(64))` |



### **5. 归一化和正则化层**
用于防止过拟合，提高模型稳定性。

| 层 | 说明 | 代码示例 |
|------|------|------|
| `BatchNormalization` | 批归一化，加速训练，提高稳定性 | `layers.BatchNormalization()` |
| `Dropout` | 随机丢弃部分神经元，防止过拟合 | `layers.Dropout(0.5)` |
| `SpatialDropout2D` | 作用于 2D 特征图的 Dropout | `layers.SpatialDropout2D(0.3)` |
| `LayerNormalization` | 层归一化（适用于 Transformer） | `layers.LayerNormalization()` |
| `GaussianNoise` | 添加高斯噪声，增强鲁棒性 | `layers.GaussianNoise(0.1)` |



### **6. 嵌入层（Embedding）**
适用于自然语言处理（NLP）。

| 层 | 说明 | 代码示例 |
|------|------|------|
| `Embedding` | 把离散整数映射到连续向量 | `layers.Embedding(input_dim=10000, output_dim=128)` |



## **7. 自注意力层（Transformer 相关）**
适用于 NLP 和序列任务。

| 层 | 说明 | 代码示例 |
|------|------|------|
| `MultiHeadAttention` | 多头自注意力机制 | `layers.MultiHeadAttention(num_heads=8, key_dim=64)` |



### **8. 其他高级层**
| 层 | 说明 | 代码示例 |
|------|------|------|
| `Concatenate` | 拼接多个张量 | `layers.Concatenate()([x1, x2])` |
| `Add` | 按元素相加 | `layers.Add()([x1, x2])` |
| `Subtract` | 按元素相减 | `layers.Subtract()([x1, x2])` |
| `Multiply` | 按元素相乘 | `layers.Multiply()([x1, x2])` |
| `Dot` | 点积计算 | `layers.Dot(axes=1)([x1, x2])` |



### **总结**
- **`Dense`**：全连接层，适用于 MLP。
- **卷积层（`Conv2D`）+ 池化层（`MaxPooling2D`）**：用于 CNN 。
- **循环层（`LSTM`，`GRU`）**：用于 RNN 任务。
- **归一化/正则化（`BatchNormalization`，`Dropout`）**：用于优化模型训练。
- **`Embedding`**：用于 NLP 任务。
- **`MultiHeadAttention`**：用于 Transformer 模型。

---

# **Keras 的基本使用方法及常见参数**  

#### **1. 导入 Keras**
```python
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
```


#### **2. 构建模型**
Keras 提供 **Sequential（顺序模型）** 和 **Functional（函数式模型）** 两种构建方式。  

##### **2.1 Sequential（顺序模型）**
适用于简单的线性堆叠网络。  

```python
model = keras.Sequential([
    layers.Dense(64, activation='relu', input_shape=(10,)),  # 输入层（10个特征）
    layers.Dense(32, activation='relu'),  # 隐藏层
    layers.Dense(1, activation='sigmoid')  # 输出层（1个神经元，适用于二分类）
])
```
##### **常见参数：**
| 参数 | 说明 | 示例 |
|------|------|------|
| `units` | 神经元个数 | `Dense(64)` |
| `activation` | 激活函数 | `'relu'`, `'sigmoid'`, `'softmax'` |
| `input_shape` | 输入特征数 | `input_shape=(10,)` |
| `kernel_initializer` | 权重初始化 | `'he_uniform'`, `'glorot_uniform'` |
| `bias_initializer` | 偏置初始化 | `'zeros'`, `'ones'` |


##### **2.2 Functional（函数式模型）**
适用于复杂网络，如多输入、多输出或共享层模型。

```python
inputs = keras.Input(shape=(10,))
x = layers.Dense(64, activation='relu')(inputs)
x = layers.Dense(32, activation='relu')(x)
outputs = layers.Dense(1, activation='sigmoid')(x)

model = keras.Model(inputs=inputs, outputs=outputs)
```



#### **3. 编译模型**
```python
model.compile(
    optimizer='adam',  # 优化器
    loss='binary_crossentropy',  # 损失函数（二分类）
    metrics=['accuracy']  # 评估指标
)
```

##### **常见参数：**
| 参数 | 说明 | 可选值 |
|------|------|------|
| `optimizer` | 优化器 | `'adam'`, `'sgd'`, `'rmsprop'`, `'adagrad'` |
| `loss` | 损失函数 | `'mse'`, `'mae'`, `'categorical_crossentropy'`, `'binary_crossentropy'` |
| `metrics` | 评估指标 | `'accuracy'`, `'mae'`, `'mse'`, `AUC()` |



#### **4. 训练模型**
```python
history = model.fit(
    X_train, y_train,  # 训练数据
    epochs=10,  # 训练轮数
    batch_size=32,  # 每批次样本数
    validation_data=(X_val, y_val)  # 验证集
)
```
##### **常见参数：**
| 参数 | 说明 | 示例 |
|------|------|------|
| `x, y` | 训练数据 | `(X_train, y_train)` |
| `epochs` | 训练轮数 | `10` |
| `batch_size` | 每批次样本数 | `32` |
| `validation_data` | 验证集 | `(X_val, y_val)` |
| `verbose` | 输出日志级别 | `0`（静默），`1`（进度条），`2`（文本） |



#### **5. 评估模型**
```python
loss, acc = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {acc:.4f}")
```



#### **6. 预测**
```python
predictions = model.predict(X_new)
```



#### **7. 保存和加载模型**
##### **7.1 保存模型**
```python
model.save('model.h5')  # 保存整个模型
```
##### **7.2 加载模型**
```python
model = keras.models.load_model('model.h5')
```

---


# tf.data 模块
- 高效构建数据输入管道
- 数据加载：支持从多种数据源（如内存数组、文件、生成器）创建数据集。
- 数据转换：提供链式操作（如 map、filter、shuffle）处理数据。
- 性能优化：通过预取（prefetch）、并行化（num_parallel_calls）和缓存（cache）加速数据流。
- 批处理与序列处理：动态批处理、填充序列（如处理变长文本）。

In [13]:
import numpy as np
input_data = np.arange(16)
input_data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [14]:
import tensorflow as tf
data_set = tf.data.Dataset.from_tensor_slices(input_data)
for data in data_set:
    print(data)

tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)
tf.Tensor(10, shape=(), dtype=int64)
tf.Tensor(11, shape=(), dtype=int64)
tf.Tensor(12, shape=(), dtype=int64)
tf.Tensor(13, shape=(), dtype=int64)
tf.Tensor(14, shape=(), dtype=int64)
tf.Tensor(15, shape=(), dtype=int64)


In [15]:
# repeat操作  重复数据集多次
data_set = data_set.repeat(2)
for data in data_set:
    print(data)

tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)
tf.Tensor(10, shape=(), dtype=int64)
tf.Tensor(11, shape=(), dtype=int64)
tf.Tensor(12, shape=(), dtype=int64)
tf.Tensor(13, shape=(), dtype=int64)
tf.Tensor(14, shape=(), dtype=int64)
tf.Tensor(15, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)
tf.Tensor(10, shape=(), dtype=int64)
tf.Tensor(11, shape=(

In [16]:
# batch操作  合并数据为批次
data_set = data_set.repeat(2).batch(4) # 4个为1批
for data in data_set:
    print(data)

tf.Tensor([0 1 2 3], shape=(4,), dtype=int64)
tf.Tensor([4 5 6 7], shape=(4,), dtype=int64)
tf.Tensor([ 8  9 10 11], shape=(4,), dtype=int64)
tf.Tensor([12 13 14 15], shape=(4,), dtype=int64)
tf.Tensor([0 1 2 3], shape=(4,), dtype=int64)
tf.Tensor([4 5 6 7], shape=(4,), dtype=int64)
tf.Tensor([ 8  9 10 11], shape=(4,), dtype=int64)
tf.Tensor([12 13 14 15], shape=(4,), dtype=int64)
tf.Tensor([0 1 2 3], shape=(4,), dtype=int64)
tf.Tensor([4 5 6 7], shape=(4,), dtype=int64)
tf.Tensor([ 8  9 10 11], shape=(4,), dtype=int64)
tf.Tensor([12 13 14 15], shape=(4,), dtype=int64)
tf.Tensor([0 1 2 3], shape=(4,), dtype=int64)
tf.Tensor([4 5 6 7], shape=(4,), dtype=int64)
tf.Tensor([ 8  9 10 11], shape=(4,), dtype=int64)
tf.Tensor([12 13 14 15], shape=(4,), dtype=int64)


In [17]:
# shuffle操作  打乱数据顺序
data_set = data_set.shuffle(buffer_size=1000)  # 缓冲区越大，随机性越强
for data in data_set:
    print(data)

tf.Tensor([12 13 14 15], shape=(4,), dtype=int64)
tf.Tensor([ 8  9 10 11], shape=(4,), dtype=int64)
tf.Tensor([0 1 2 3], shape=(4,), dtype=int64)
tf.Tensor([0 1 2 3], shape=(4,), dtype=int64)
tf.Tensor([12 13 14 15], shape=(4,), dtype=int64)
tf.Tensor([4 5 6 7], shape=(4,), dtype=int64)
tf.Tensor([ 8  9 10 11], shape=(4,), dtype=int64)
tf.Tensor([0 1 2 3], shape=(4,), dtype=int64)
tf.Tensor([4 5 6 7], shape=(4,), dtype=int64)
tf.Tensor([4 5 6 7], shape=(4,), dtype=int64)
tf.Tensor([4 5 6 7], shape=(4,), dtype=int64)
tf.Tensor([12 13 14 15], shape=(4,), dtype=int64)
tf.Tensor([12 13 14 15], shape=(4,), dtype=int64)
tf.Tensor([0 1 2 3], shape=(4,), dtype=int64)
tf.Tensor([ 8  9 10 11], shape=(4,), dtype=int64)
tf.Tensor([ 8  9 10 11], shape=(4,), dtype=int64)
